Initialize dotfiles only when given init option

diff --git a/etc/install b/etc/install
--- a/etc/install
+++ b/etc/install
@@ -139,14 +139,17 @@ dotfiles_deploy() {
 }
 
 dotfiles_initialize() {
-  e_newline && e_header "Initializing dotfiles..."
+  # bash -c "$(curl -fsSL https://raw.githubusercontent.com/Atsuyoshi-N/dotfiles/master/etc/install) -s init
+  if [ "$1" = "init" ]; then
+    e_newline && e_header "Initializing dotfiles..."
 
-  if [ -f Makefile ]; then
-    make init &&
-    e_newline && e_done "Initialized"
-  else
-    log_fail "Makefile: not found"
-    exit 1
+    if [ -f Makefile ]; then
+      make init &&
+      e_newline && e_done "Initialized"
+    else
+      log_fail "Makefile: not found"
+      exit 1
+    fi
   fi
 }
 
